import React from 'react';
const About = () => {
    return(
        <span>

        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus porttitor nisl lacus, ac convallis leo convallis in. Sed rutrum, est vitae sollicitudin sodales, nulla ante posuere orci, ac mattis urna risus sit amet nisi. Fusce pellentesque tortor elit, a molestie justo fermentum eu. Praesent dictum ullamcorper erat, vel condimentum leo mattis at. Suspendisse ligula turpis, fringilla ac pellentesque volutpat, auctor vitae felis. Sed feugiat pulvinar tellus, sed dignissim orci elementum a. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In at tempus odio. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Phasellus sit amet vulputate arcu, et volutpat ipsum. Donec nec ullamcorper velit. Ut a interdum leo.
        
        Suspendisse pulvinar id turpis id porta. Curabitur odio augue, auctor eu tempor nec, interdum eget dui. Curabitur fringilla lectus vitae libero consectetur eleifend. Cras volutpat at libero non ullamcorper. Quisque imperdiet suscipit mauris. Suspendisse eleifend eros vitae arcu egestas, nec pulvinar magna tempor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In ut magna mauris. Mauris pellentesque metus eget convallis varius. Integer tincidunt consectetur laoreet. Nunc mattis ipsum ut metus venenatis, sit amet convallis nisl scelerisque. Aenean dui ligula, egestas et lacus ac, tincidunt interdum urna. Vestibulum et auctor sapien. Aliquam viverra erat urna, eget rutrum velit tempus non. Ut convallis justo euismod massa consequat elementum.
        
        Etiam at sem aliquet, bibendum est nec, efficitur turpis. Fusce lectus arcu, semper nec enim sit amet, dapibus efficitur sem. Duis a dui porttitor, condimentum sem a, tincidunt dui. Suspendisse potenti. Ut magna tortor, sagittis eget ligula vitae, convallis vestibulum mauris. Nunc fermentum ultrices ipsum, nec pulvinar massa tincidunt vitae. Vestibulum quis quam vel diam scelerisque imperdiet. Vestibulum a interdum quam. Integer porttitor elementum sapien et pellentesque. Mauris sodales eget diam at dapibus. Etiam nec ullamcorper lorem. Ut ligula velit, finibus quis dolor in, volutpat tempor erat. Maecenas nec volutpat odio. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec nec diam odio.
        
        Proin ut odio dictum magna vehicula mollis quis id tellus. Integer nunc turpis, vehicula id facilisis sit amet, vulputate sollicitudin massa. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec consectetur, felis eu commodo suscipit, augue ipsum pretium lectus, quis pulvinar eros odio in felis. Mauris eu justo ultricies, dictum nibh ac, placerat arcu. In turpis leo, consectetur malesuada felis luctus, congue tempor sem. Phasellus ullamcorper interdum eros a pharetra. Duis velit ligula, interdum ac mi ac, commodo placerat quam. Aliquam tincidunt diam eu eros mollis, id placerat sem consectetur. Vestibulum elit enim, feugiat id accumsan vitae, ornare eget justo. Curabitur eleifend ante orci, et tristique felis ullamcorper ac. Donec eget odio varius ex fermentum ornare vitae efficitur ante. Etiam in quam diam.
        
        Vestibulum faucibus auctor nunc, a lobortis augue mattis non. Sed in tellus mollis, placerat ligula vel, eleifend est. Pellentesque tempor et urna eu vulputate. Vestibulum cursus, velit sed suscipit finibus, diam felis volutpat nunc, sagittis laoreet sem erat quis mi. Ut eu neque lacus. Donec eu varius tortor. Nulla finibus tempus tempus. Aenean fringilla neque eu ipsum molestie viverra. Vivamus varius mi quis turpis fringilla dignissim. Sed non tincidunt eros. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed a orci fermentum, iaculis nibh eget, fringilla eros. Phasellus sit amet condimentum purus, et lacinia mauris. </span>
    )
}

export default About